# Generated by Django 2.2.10 on 2022-02-20 04:42

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='Комментарий')),
                ('data_created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('активный', 'активный'), ('удален за оскорбление', 'удален за оскорбление'), ('удален за нарушение цензуры', 'удален за нарушение цензуры')], default='активный', max_length=35, verbose_name='Статус')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Удален')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Теги')),
                ('data_created', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Удален')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500, verbose_name='Вопрос')),
                ('slag', models.SlugField(allow_unicode=True, max_length=500, verbose_name='Слаг')),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Ответ')),
                ('data_created', models.DateField(auto_now_add=True, verbose_name='дата создания')),
                ('status', models.CharField(blank=True, choices=[('активный', 'активный'), ('в процессе', 'в процессе'), ('возвращен', 'возвращен'), ('принят', 'принят'), ('удален', 'удален')], default='в процессе', max_length=15, verbose_name='Статус')),
                ('pro', models.BooleanField(default=False, verbose_name='pro подписка')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Удален')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Comment', verbose_name='Комментарии')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'questions',
            },
        ),
    ]
