# Generated by Django 2.2.10 on 2022-03-19 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_questions', models.DecimalField(decimal_places=0, default=0, max_digits=2, verbose_name='Количество вопросов')),
                ('data_workout', models.DateField(auto_now_add=True, verbose_name='Дата тренировки')),
                ('average_score', models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Средний балл тренировки')),
                ('is_delete', models.BooleanField(default=False, verbose_name='Удалена')),
            ],
            options={
                'verbose_name': 'Тренировка',
                'verbose_name_plural': 'Тренировки',
                'db_table': 'workouts',
            },
        ),
        migrations.CreateModel(
            name='WorkoutQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], decimal_places=0, default=0, max_digits=1, verbose_name='Оценка')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='questions.Question', verbose_name='Вопросы')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.Workout', verbose_name='Тренировка')),
            ],
            options={
                'verbose_name': 'Вопрос тренировки',
                'verbose_name_plural': 'Вопросы тренировки',
                'db_table': 'workout_questions',
            },
        ),
        migrations.AddField(
            model_name='workout',
            name='questions',
            field=models.ManyToManyField(through='workouts.WorkoutQuestion', to='questions.Question', verbose_name='Вопросы'),
        ),
        migrations.AddField(
            model_name='workout',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
