# Generated by Django 2.2.10 on 2022-02-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='name',
            field=models.CharField(default='name', max_length=25, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workoutquestion',
            name='rating',
            field=models.DecimalField(choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1), (0, 0)], decimal_places=0, default=0, max_digits=1, verbose_name='Оценка'),
        ),
    ]
