# Generated by Django 2.2.10 on 2022-03-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20220321_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workoutquestion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workoutquestion',
            name='rating',
            field=models.DecimalField(choices=[(5, 5), (4, 4), (3, 3), (2, 2)], decimal_places=0, default=2, max_digits=1, verbose_name='Оценка'),
        ),
    ]
